weather:
  # Get API Key from https://openweathermap.org/appid
  api_key: xxx
  # City IDs can be found at http://bulk.openweathermap.org/sample/
  # Defaults to London, New York and San Francisco
  city_ids: "2643743,1689973,5391959"
  unit: metric
  main_city: "Madrid,ES"

signalfx:
  access_token: xxx
  realm: us0
  chart_id: xxx
